# AstraLink Private Blockchain Network Configuration

network:
  name: "AstraLink_Private_Network"
  chain_id: 8453  # Base chain ID
  consensus: "PoA"  # Proof of Authority
  block_time: 5  # 5 second blocks for fast eSIM operations
  network_type: "mainnet"
  rpc_endpoint: "https://mainnet.base.org"

dns:
  domain: "quantum.api"
  bootstrap_nodes:
    - "node1.quantum.api"
    - "node2.quantum.api"
    - "node3.quantum.api"
  api_endpoints:
    - "api.quantum.api"
    - "rpc.quantum.api"

validators:
  min_validators: 3
  max_validators: 7
  requirements:
    - "Telecom License"
    - "Hardware Security Module"
    - "Quantum-Safe Cryptography Support"

privacy:
  transaction_privacy: true
  zk_snarks: true
  quantum_resistant: true
  data_encryption: "post-quantum"

smart_contracts:
  gas_limit: 2000000
  contract_abi_path: "blockchain/abi/esim_nft.json"
  deployment:
    - name: "ESIMRegistry"
      address: "0x..."
    - name: "PrivacyLayer"
      address: "0x..."
    - name: "TelecomVerifier"
      address: "0x..."

handshake_integration:
  enabled: true
  api_endpoint: "http://localhost:12037"
  nameservers:
    - "103.196.38.38"  # HNS.to primary
    - "103.196.38.39"  # HNS.to secondary
    - "172.104.213.10" # HDNS.io
  domain: "quantum.api"
  records:
    - name: "node1"
      type: "A"
      value: "10.0.1.1"
    - name: "node2"
      type: "A"
      value: "10.0.1.2"
    - name: "node3"
      type: "A"
      value: "10.0.1.3"
    - name: "_api._tcp"
      type: "SRV"
      value: "0 5 443 api.quantum.api"
    - name: "_blockchain._tcp"
      type: "SRV"
      value: "0 5 8545 rpc.quantum.api"
    - name: "_quantum._tcp"
      type: "SRV"
      value: "0 5 9000 quantum.quantum.api"
  dnssec:
    enabled: true
    key_algorithm: "ED25519"
    refresh_interval: 86400  # 24 hours

security:
  quantum_safe_algorithms:
    - "Dilithium"  # For digital signatures
    - "Kyber"      # For key encapsulation
  firewall_rules:
    - "Allow P2P: 30303"
    - "Allow RPC: 8545 (private nodes only)"
    - "Allow API: 443"

monitoring:
  metrics_endpoint: "metrics.quantum.api"
  health_check: "health.quantum.api"
  alert_webhook: "alerts.quantum.api"