# AstraLink Security Auditor Configuration
# =======================================

# Global settings
audit_interval: "1d"  # Run audits daily
report_retention: "30d"  # Keep reports for 30 days
notification_channels:
  - "security_team"
  - "syslog"

# Vulnerability scanning
vulnerability_scan:
  enabled: true
  scanner: "openvas"  # Or "nessus", "qualys"
  severity_threshold: "high"  # Only report high-severity vulnerabilities
  report_format: "html"
  
# Compliance checking
compliance_check:
  enabled: true
  standards:
    - "CIS"
    - "AstraLink-Security-Policy"
  baseline_profile: "strict"
  remediation_steps: true  # Include remediation steps in report

# Intrusion detection
intrusion_detection:
  enabled: true
  ids_engine: "snort"  # Or "suricata", "bro"
  alert_level: "high"  # Only report high-severity alerts
  response_actions:
    - "block_ip"
    - "quarantine_node"
  
# Log analysis
log_analysis:
  enabled: true
  log_source: "systemd"  # Or "splunk", "elk"
  security_events:
    - "authentication_failure"
    - "unauthorized_access"
    - "malware_detection"
  anomaly_detection:
    algorithm: "statistical"
    threshold: 3  # Standard deviations from baseline

# Quantum security validation
quantum_security:
  enabled: true
  key_exchange_protocol: "Kyber-1024"
  encryption_algorithm: "AES-256-GCM"
  error_correction_algorithm: "surface_code"
  minimum_qubit_lifetime: "1s"
  minimum_entanglement_fidelity: 0.999
  
# Reporting
report_format: "pdf"  # Or "html", "json"
report_delivery:
  method: "email"
  recipients:
    - "security@quantum.api"
    - "ops@quantum.api"
  encryption: true
  
# Remediation
auto_remediation: false  # Set to true for automated remediation (CAUTION)
remediation_approval: true  # Require approval before applying changes
remediation_steps:
  - "update_packages"
  - "harden_configuration"
  - "isolate_node"

# API Keys
api_keys:
  astra_admin: "your_strong_api_key_here"