
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - open5gs_network

  open5gs:
    build:
      context: ../..
      dockerfile: Dockerfile.open5gs
    container_name: open5gs
    depends_on:
      - mongodb
    networks:
      - open5gs_network
    volumes:
      - ./config:/etc/open5gs
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

  astralink-controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: astralink-controller
    depends_on:
      - open5gs
    networks:
      - open5gs_network
    environment:
      - SMART_CONTRACT_ADDRESS=${SMART_CONTRACT_ADDRESS}
      - WEB3_PROVIDER=${WEB3_PROVIDER}
      - TECH_OWNER_WALLET=${TECH_OWNER_WALLET}

networks:
  open5gs_network:
    driver: bridge

volumes:
  mongodb_data:
