# AstraLink Hybrid Edge-Satellite Node Configuration
# ============================================
# Optimized for remote areas with combined edge computing and satellite connectivity

network:
  node_id: "hybrid-remote-1"
  domain: "hybrid1.quantum.api"
  environment: "mainnet"
  role: "hybrid_edge_satellite"
  region: "remote-us-west"
  deployment_type: "off_grid"

quantum:
  error_correction:
    algorithm: "surface_code_adaptive"
    error_threshold: 0.0005
    memory_limit: "32G"
    environmental_compensation: true  # Adapt to harsh conditions
  entanglement:
    pairs: 1024
    lifetime: "1s"
    mode: "hybrid_optimization"
    satellite_link_priority: true
  security:
    encryption: "Kyber-1024"
    authentication: "Dilithium-4"
    environmental_hardening: true

satellite:
  primary_provider:
    name: "starlink"
    enabled: true
    frequencies:
      uplink: "14.0-14.5 GHz"
      downlink: "10.7-12.7 GHz"
    beam_forming:
      enabled: true
      tracking: "adaptive"
      elements: 128
    quantum_link:
      enabled: true
      wavelength: "1550nm"
      protocol: "BB84"
  
  backup_provider:
    name: "outernet"
    enabled: true
    mode: "failover"
    frequencies:
      uplink: "5.0-5.2 GHz"
      downlink: "3.7-4.2 GHz"
  
  link_optimization:
    weather_compensation: true
    adaptive_power: true
    quantum_error_mitigation: true

edge_compute:
  services:
    - name: "local_cache"
      memory: "64G"
      strategy: "quantum_assisted"
      offline_capability: true
    - name: "content_delivery"
      storage: "10TB"
      caching: "predictive_offline"
    - name: "emergency_services"
      priority: "critical"
      always_available: true
  optimization:
    latency_target: "5ms"
    offline_mode_ready: true
    power_efficiency: "maximum"

cellular:
  stack_type: "3GPP"
  features:
    - "5G"
    - "Edge Computing"
    - "Satellite Backhaul"
    - "Emergency Services"
  sdr:
    enabled: true
    hardware: "USRP_N320"
    sample_rate: 100000000  # 100 MHz bandwidth
    gain: 50
    channels: 4
    power_saving: true
  capacity:
    max_users: 5000
    bandwidth: "5Gbps"
    optimization: "reliability_first"

power_management:
  sources:
    - type: "solar"
      capacity: "20kW"
      storage: "100kWh"
    - type: "fuel_cell"
      capacity: "10kW"
      runtime: "72h"
  optimization:
    mode: "efficient"
    priority_services:
      - "emergency_communications"
      - "quantum_links"
      - "satellite_uplink"
  backup:
    duration: "72h"
    critical_services_only: true

blockchain:
  chain_id: 22625
  network: "mainnet"
  consensus:
    role: "lightweight_validator"
    stake: "25000"
  offline_operation:
    enabled: true
    sync_strategy: "periodic"
    local_validation: true

handshake:
  domain: "quantum.api"
  records:
    - type: "A"
      name: "hybrid1"
      value: "${NODE_IP}"
    - type: "SRV"
      name: "_hybrid"
      target: "hybrid1.quantum.api"
      port: 443
  offline_resolution:
    enabled: true
    cache_duration: "24h"

monitoring:
  metrics:
    collection_interval: "1s"
    retention: "14d"
    offline_buffer: "7d"
    quantum_metrics:
      - "decoherence_rate"
      - "error_correction_success"
      - "satellite_link_quality"
    edge_metrics:
      - "service_availability"
      - "power_consumption"
      - "storage_usage"
    environmental_metrics:
      - "temperature"
      - "humidity"
      - "solar_conditions"
  alerts:
    error_rate_threshold: 0.005
    power_threshold: "20%"
    satellite_link_threshold: "70%"
    notification_channels:
      - "satellite_notification"
      - "local_display"
      - "emergency_broadcast"

security:
  encryption:
    symmetric: "AES-256-GCM"
    asymmetric: "Kyber-1024"
    offline_keys:
      rotation: "7d"
      backup: true
  authentication:
    method: "quantum_challenge_response"
    offline_capable: true
    local_validation: true
  physical_security:
    sensors: true
    tamper_detection: true
    gps_monitoring: true

resilience:
  environmental:
    operating_range: "-40C to +60C"
    humidity: "0-100%"
    dust_protection: "IP67"
  redundancy:
    satellite_links: 2
    storage_arrays: "raid10"
    power_systems: "n+1"
  failover:
    detection_time: "10ms"
    satellite_to_cache: "50ms"
    power_switching: "0ms"

disaster_recovery:
  backup_schedule: "hourly"
  offline_operation:
    max_duration: "30d"
    service_priorities:
      - "emergency_communications"
      - "local_services"
      - "essential_computing"
  data_preservation:
    strategy: "quantum_redundant"
    georeplication: true

maintenance:
  remote_management:
    satellite_based: true
    quantum_secured: true
  autonomous_operation:
    self_healing: true
    predictive_maintenance: true
  physical_access:
    authentication: "multi_factor"
    logging: "tamper_proof"

compliance:
  standards:
    - "ISO27001"
    - "NIST-PQC"
    - "Emergency-Services-Act"
  certification_level: "critical_infrastructure"
  audit_schedule: "quarterly"
  data_sovereignty: "local_first"