# AstraLink IoT Gateway Node Configuration
# =======================================
# Optimized for massive device connectivity, low power consumption, and quantum-safe data aggregation

network:
  node_id: "iot-gateway-1"
  domain: "iot1.quantum.api"
  environment: "mainnet"
  role: "iot_gateway"
  location: "urban"
  power_source: "grid"

quantum:
  error_correction:
    algorithm: "ldpc_lightweight"
    error_threshold: 0.001
    memory_limit: "8G"
    energy_efficiency: true
  entanglement:
    pairs: 256
    lifetime: "100ms"
    mode: "local_aggregation"
  security:
    encryption: "Kyber-512"
    authentication: "Dilithium-2"
    low_power_mode: true

cellular:
  stack_type: "NB-IoT"  # Narrowband IoT
  features:
    - "Low Power Wide Area"
    - "Massive Device Connectivity"
    - "Quantum-Secured Backhaul"
  sdr:
    enabled: false  # No SDR for NB-IoT
  capacity:
    max_devices: 100000
    bandwidth: "10Mbps"
    power_saving_mode: true
    deep_sleep_mode: true

iot:
  protocols:
    - "MQTT"
    - "CoAP"
    - "LoRaWAN"
  data_aggregation:
    algorithm: "quantum_hashing"
    anonymization: true
    compression: "quantum_aware"
  device_management:
    firmware_updates: "quantum_secured"
    remote_control: "authorized_devices_only"
  security:
    device_authentication: "quantum_challenge_response"
    data_encryption: "end_to_end"
    access_control: "role_based"

blockchain:
  chain_id: 22625
  network: "mainnet"
  consensus:
    role: "data_aggregator"
    stake: "1000"
  data_storage:
    strategy: "quantum_encrypted"
    offchain_storage: true
  contracts:
    data_registry:
      access_control: "permissioned"
      audit_trail: true

handshake:
  domain: "quantum.api"
  records:
    - type: "A"
      name: "iot1"
      value: "${NODE_IP}"
    - type: "SRV"
      name: "_iot"
      target: "iot1.quantum.api"
      port: 443
  security:
    dnssec: true
    quantum_signing: true

monitoring:
  metrics:
    collection_interval: "10s"
    retention: "30d"
    quantum_metrics:
      - "decoherence_rate"
      - "error_correction_success"
      - "key_generation_rate"
    iot_metrics:
      - "device_connectivity"
      - "data_throughput"
      - "power_consumption"
      - "security_events"
  alerts:
    device_loss_threshold: 0.1
    data_integrity_threshold: 0.001
    power_consumption_threshold: "90%"
    notification_channels:
      - "security_team"
      - "network_ops"
      - "syslog"

security:
  encryption:
    symmetric: "ChaCha20-Poly1305"  # Low power
    asymmetric: "Kyber-512"
  authentication:
    method: "quantum_challenge_response"
    device_level: true
    key_rotation: "daily"
  access_control:
    rbac_enabled: true
    quantum_verification: true
  data_validation:
    anomaly_detection: "ai_powered"
    tamper_resistance: true
  firmware_security:
    signed_updates: true
    rollback_protection: true

power:
  source: "grid"
  consumption_target: "5W"
  optimization:
    mode: "aggressive"
    sleep_cycles: true
    adaptive_clocking: true
  backup:
    duration: "24h"
    critical_functions_only: true

resilience:
  network_diversity:
    cellular: true
    lorawan: true
    satellite: false
  data_replication:
    strategy: "quantum_redundant"
    local_cache: true
  failover:
    detection_time: "100ms"
    recovery_time: "1s"

compliance:
  standards:
    - "ISO27001"
    - "GDPR"
    - "IoT-Security-Best-Practices"
  data_minimization: true
  privacy_by_design: true
  audit_schedule: "annually"