# AstraLink Satellite Uplink Node Configuration
# =========================================
# Optimized for satellite connectivity and quantum-safe communication

network:
  node_id: "sat-uplink-1"
  domain: "sat1.quantum.api"
  environment: "mainnet"
  role: "satellite_uplink"

quantum:
  error_correction:
    algorithm: "lattice_surgery"
    error_threshold: 0.00001  # Ultra-strict for space-based quantum links
    memory_limit: "64G"  # Large memory for quantum state preservation
  entanglement:
    pairs: 2048
    lifetime: "2s"
    distance: "orbital"  # Optimized for satellite distances
  security:
    encryption: "Kyber-1024"
    authentication: "Dilithium-5"
    space_hardened: true  # Additional protection for space environment

satellite:
  providers:
    starlink:
      enabled: true
      frequencies:
        uplink: "14.0-14.5 GHz"
        downlink: "10.7-12.7 GHz"
      beam_forming:
        enabled: true
        tracking: "adaptive"
        elements: 256
      quantum_link:
        enabled: true
        wavelength: "1550nm"
        protocol: "BB84"
    
    outernet:
      enabled: true
      mode: "high_reliability"
      frequencies:
        uplink: "5.0-5.2 GHz"
        downlink: "3.7-4.2 GHz"
  
  tracking:
    system: "quantum_enhanced"
    precision: "0.001deg"
    update_rate: "1000Hz"
  
  redundancy:
    active_links: 4
    failover_time: "50ms"
    diversity_scheme: "spatial"

cellular:
  stack_type: "3GPP"
  features:
    - "5G"
    - "Satellite Backhaul"
  sdr:
    enabled: true
    hardware: "USRP_N320"
    sample_rate: 200000000  # 200 MHz bandwidth
    gain: 60
    channels: 8  # Enhanced MIMO for satellite
  capacity:
    max_bandwidth: "10Gbps"
    latency_target: "50ms"

blockchain:
  chain_id: 22625
  network: "mainnet"
  consensus:
    role: "validator"
    stake: "50000"
  contracts:
    satellite_bandwidth:
      allocation_strategy: "priority_based"
      quantum_verification: true

handshake:
  domain: "quantum.api"
  records:
    - type: "A"
      name: "sat1"
      value: "${NODE_IP}"
    - type: "SRV"
      name: "_satellite"
      target: "sat1.quantum.api"
      port: 443
  security:
    dnssec: true
    quantum_signing: true

monitoring:
  metrics:
    collection_interval: "100ms"
    retention: "30d"
    quantum_metrics:
      - "decoherence_rate"
      - "entanglement_fidelity"
      - "quantum_bit_error_rate"
      - "key_generation_rate"
    satellite_metrics:
      - "signal_strength"
      - "pointing_accuracy"
      - "link_quality"
      - "doppler_shift"
      - "phase_noise"
    environmental_metrics:
      - "temperature"
      - "radiation_level"
      - "magnetic_field"
  alerts:
    error_rate_threshold: 0.0001
    pointing_error_threshold: "0.01deg"
    quantum_error_threshold: 0.00001
    notification_channels:
      - "mission_control"
      - "pager"
      - "email"

security:
  encryption:
    symmetric: "AES-256-GCM"
    asymmetric: "Kyber-1024"
    space_hardening:
      radiation_resistant: true
      error_detection: "enhanced"
  authentication:
    method: "quantum_challenge_response"
    mfa_required: true
    space_qualified: true
  access_control:
    rbac_enabled: true
    quantum_verification: true
  audit_logging:
    enabled: true
    retention: "7y"
    encryption: true

performance:
  cpu_allocation:
    quantum_processes: "40%"
    satellite_control: "40%"
    blockchain: "20%"
  memory_limits:
    quantum_operations: "64G"
    satellite_stack: "32G"
    blockchain: "16G"
  io_priority:
    satellite: "realtime"
    quantum: "high"
    blockchain: "medium"

resilience:
  radiation_protection:
    error_correction: "triple_modular"
    memory_scrubbing: true
    interval: "1s"
  thermal_management:
    active_cooling: true
    temperature_range: "-40C to +85C"
  power_management:
    redundant_supply: true
    quantum_safe_mode: true

compliance:
  standards:
    - "ISO27001"
    - "NIST-PQC"
    - "Space-QKD-1"
    - "ITU-T-Q.Space"
  certification_level: "space_grade"
  audit_schedule: "monthly"