# AstraLink Mainnet Configuration
# ==============================
# Production configuration with maximum security and optimized performance

network_stack:
  3gpp:
    enabled: true
    debug_mode: false
    mock_hardware: false
    amf:
      capacity: 1000000  # Support 1M connected devices
      features:
        - "5G"
        - "Network Slicing"
        - "Edge Computing"
        - "URLLC"  # Ultra-Reliable Low-Latency Communication
      security:
        quantum_safe: true
        encryption: "Kyber-1024"  # Maximum security
        authentication: "Dilithium-5"

    smf:
      upf_selection: "performance_and_latency"
      session_rules:
        max_bandwidth: "10Gbps"
        latency_class: "ultra-low"
      redundancy: true
      failover_time: "50ms"

sdr_interface:
  hardware:
    type: "USRP_X310"  # High-performance SDR
    sample_rate: 100000000  # 100 MHz bandwidth
    center_freq: 3500000000  # 3.5 GHz (n78 band)
    gain: 50
    antenna: "TX/RX"
    features:
      - "MIMO_4X4"
      - "Beamforming"
  
  modulation:
    scheme: "adaptive_quantum_safe"
    modes:
      - "QPSK"
      - "16QAM"
      - "64QAM"
      - "256QAM"
      - "1024QAM"
    error_correction: "quantum_ldpc_enhanced"

satellite:
  providers:
    starlink:
      enabled: true
      frequencies:
        uplink: "14.0-14.5 GHz"
        downlink: "10.7-12.7 GHz"
      beam_forming: true
      quantum_encryption: true
    outernet:
      enabled: true
      mode: "high_reliability"
  redundancy:
    min_providers: 2
    failover_time: "100ms"

blockchain:
  network: "mainnet"
  chain_id: 22625
  consensus:
    type: "PoA"
    block_time: 5  # 5 second blocks
    validators:
      min: 7
      max: 11
      selection: "reputation_based"
  contracts:
    auto_deploy: false
    gas_optimization: true
    audit_required: true
  security:
    multisig_threshold: 5
    hardware_signing: true

quantum:
  simulation_mode: false
  error_correction:
    enabled: true
    algorithm: "surface_code_enhanced"
    threshold: 0.0001
    recovery_time: "1ms"
  redundancy:
    active_qubits: 1024
    error_margin: "1e-10"

handshake:
  domain: "quantum.api"
  records:
    - type: "A"
      name: "mainnet.quantum.api"
      value: "${NODE_IP}"
    - type: "AAAA"
      name: "mainnet.quantum.api"
      value: "${NODE_IPV6}"
    - type: "SRV"
      name: "_blockchain._tcp.quantum.api"
      target: "chain.quantum.api"
  security:
    dnssec: true
    quantum_signing: true

security:
  development_mode: false
  allow_unsafe_operations: false
  encryption:
    symmetric: "AES-256-GCM"
    asymmetric: "Kyber-1024"
    post_quantum: true
  authentication:
    method: "quantum_challenge_response"
    hardware_backed: true
    mfa_required: true
  access_control:
    rbac_enabled: true
    quantum_verification: true
  audit_logging:
    enabled: true
    storage_duration: "7y"
    encryption: true

monitoring:
  debug_level: "info"
  performance_tracking: true
  metrics:
    collection_interval: "1s"
    storage_duration: "365d"
    quantum_metrics:
      - "decoherence_rate"
      - "error_correction_success"
      - "entanglement_fidelity"
      - "qubit_lifetime"
    network_metrics:
      - "bandwidth_usage"
      - "latency"
      - "packet_loss"
      - "error_rate"
      - "quantum_state_quality"
  alerts:
    error_rate_threshold: 0.001
    latency_threshold: "10ms"
    quantum_error_threshold: 0.0001
    notification_channels:
      - "pager"
      - "email"
      - "slack"

performance:
  cpu_allocation:
    quantum_processes: "70%"
    network_processes: "20%"
    blockchain_processes: "10%"
  memory_limits:
    quantum_operations: "64G"
    network_stack: "32G"
    blockchain: "16G"
  io_priority:
    quantum: "realtime"
    network: "high"
    blockchain: "medium"

disaster_recovery:
  backup_interval: "1h"
  backup_retention: "90d"
  geo_redundancy: true
  recovery_time_objective: "5m"
  recovery_point_objective: "1m"

compliance:
  standards:
    - "ISO27001"
    - "GDPR"
    - "HIPAA"
    - "PCI-DSS"
  audit_schedule: "quarterly"
  data_retention: "7y"