
name: AstraLink Genesis Bot Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'astra-genesis/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Deployment
        run: |
          python deploy.py
        env:
          ASTRA_API_KEY: ${{ secrets.ASTRA_API_KEY }}
          APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Enable Log Management
        uses: actions/cache@v3
        with:
          path: artifact_logs
          key: astra_log_${{ github.run_number }}
