name: AstraLink Genesis Bot Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'astra-genesis/*'

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@vs
    - name: Setup Python
        uses: actions/setup-python@vs
        with:
          python-version: '3.9'

    - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4

    - name: Run Bot Deployment
        run: |
          python astra-genesis/genesis-bot/microtask-bot.py

    - name: Commit and Push Changes
        run: |
          git config --global user.name AstraBot
          git config --global user.email bot@astralink.com
          git add .
          git commit -m "Automated Genesis Bot Deployment"
          git push